# -*- coding: utf-8 -*-
"""Sistem Peramalan (Forecasting) Penjualan Toko

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaqvJ57og5Qg8Y-0zMVHvajK-y_e33wu
"""

import pandas as pd
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
import pickle # Ditambahkan untuk menyimpan model

# [PENTING]: Pastikan Anda sudah menginstall library prophet
# Jalankan command ini di terminal Anda: pip install prophet
try:
    from prophet import Prophet
except ImportError:
    print("WARNING: Library 'prophet' belum terinstall. Silakan install dengan: pip install prophet")

from sklearn.metrics import mean_squared_error, mean_absolute_error

# ==============================================================================
# 1. DATA INGESTION & PREPROCESSING (ETL PIPELINE)
# ==============================================================================
def load_and_preprocess_data():
    """
    Fungsi ini membaca semua file Excel transaksi (termasuk multi-sheet),
    menggabungkannya (Union), dan membersihkan format tanggal.
    """
    print("[1] Memulai Proses Ekstraksi Data (ETL)...")
    file_list = glob.glob("*.xlsx") # Mencari semua file Excel di folder
    df_list = []

    if file_list:
        print(f"Ditemukan {len(file_list)} file Excel untuk di-union.")
        for file in file_list:
            if file != "combined_sales_data.csv": # Tetap asumsikan output backup adalah CSV
                try:
                    # Membaca setiap file Excel, termasuk multi-sheet
                    all_sheets = pd.read_excel(file, sheet_name=None)
                    # Menggabungkan semua sheet menjadi satu DataFrame sementara
                    temp_df = pd.concat(all_sheets.values(), ignore_index=True)
                    df_list.append(temp_df)
                    print(f"  - Berhasil membaca: {file} ({len(all_sheets)} sheet, {temp_df.shape[0]} baris gabungan)")
                except Exception as e:
                    pass # Abaikan error baca untuk menjaga kelancaran pipeline

        if df_list:
            df = pd.concat(df_list, ignore_index=True)
            print(f"Union sukses! Total data mentah: {df.shape[0]} transaksi.")
            # (Opsional) Menyimpan hasil union ke satu file untuk backup
            df.to_csv("combined_sales_data.csv", index=False)
        else:
             df = buat_data_sampel()
    else:
        print("WARNING: Tidak ada file Excel ditemukan. Menggunakan Dummy Data untuk simulasi Prophet...")
        df = buat_data_sampel()

    # Standarisasi Tanggal
    df['Tanggal'] = pd.to_datetime(df['Tanggal'], errors='coerce')
    df = df.dropna(subset=['Tanggal'])
    df = df.sort_values('Tanggal')

    # FEATURE ENGINEERING (Ekstraksi informasi dari Tanggal)
    # Ini penting agar model Machine Learning bisa mengerti konsep waktu
    df['Bulan'] = df['Tanggal'].dt.month
    df['Hari_Dalam_Minggu'] = df['Tanggal'].dt.dayofweek # 0=Senin, 6=Minggu
    df['Apakah_Akhir_Pekan'] = df['Hari_Dalam_Minggu'].apply(lambda x: 1 if x >= 5 else 0)

    return df

def buat_data_sampel():
    """Fungsi helper jika file CSV tidak ditemukan di direktori."""
    print("WARNING: Menggunakan Dummy Data untuk simulasi Prophet...")
    # Membuat rentang waktu harian selama 100 hari
    dates = pd.date_range(start="2025-09-01", periods=100)
    # Membuat data penjualan acak dengan sedikit tren naik
    np.random.seed(42)
    sales = np.random.randint(1000000, 10000000, size=100) + (np.arange(100) * 50000)
    return pd.DataFrame({'Tanggal': dates, 'Total (Rp)': sales})

# ==============================================================================
# 2. DATA TRANSFORMATION UNTUK FACEBOOK PROPHET
# ==============================================================================
def prepare_prophet_data(df):
    """
    Facebook Prophet WAJIB memiliki format DataFrame dengan 2 kolom:
    1. 'ds' (datestamp) -> Tanggal transaksi
    2. 'y' (target)     -> Nilai numerik yang ingin diramal (Misal: Total Omzet)
    """
    print("[2] Mentransformasi data ke format Facebook Prophet (ds & y)...")

    # Karena dalam 1 hari bisa ada >1 transaksi, kita jumlahkan dulu (Aggregasi Harian)
    df_daily = df.groupby('Tanggal')['Total (Rp)'].sum().reset_index()

    # Rename kolom sesuai standar Prophet
    df_prophet = df_daily.rename(columns={
        'Tanggal': 'ds',
        'Total (Rp)': 'y'
    })

    print(f"Transformasi selesai. Data siap di-training: {df_prophet.shape[0]} hari aktif.")
    return df_prophet

# ==============================================================================
# 3. TRAINING & EVALUASI MODEL TIME-SERIES
# ==============================================================================
def train_and_evaluate_prophet(df_prophet):
    """
    Melatih model Prophet dan mengevaluasi error-nya.
    Pemotongan data (Train/Test Split) tidak boleh acak, harus berurutan secara waktu!
    """
    print("[3] Memulai proses Training Model Facebook Prophet...")

    # A. Chronological Split (80% Training, 20% Testing)
    # Kita pakai 80% data terlama untuk belajar, 20% data terbaru untuk ujian.
    split_index = int(len(df_prophet) * 0.8)
    train_df = df_prophet.iloc[:split_index]
    test_df = df_prophet.iloc[split_index:]

    # B. Inisialisasi Model Prophet
    # Anda bisa menyalakan efek liburan nasional jika mau, di sini kita pakai standar dulu
    model = Prophet(
        daily_seasonality=False, # Data kita harian, bukan jam-jaman
        yearly_seasonality=False, # Data kita belum mencapai 1 tahun (hanya 5 bulan)
        weekly_seasonality=True   # Turis biasanya punya pola mingguan (ramai di weekend)
    )

    # C. Training (Fitting)
    model.fit(train_df)

    # D. Prediksi pada data Testing (untuk evaluasi)
    forecast_test = model.predict(test_df[['ds']])

    # E. Kalkulasi Error (RMSE & MAE)
    y_asli = test_df['y'].values
    y_prediksi = forecast_test['yhat'].values # yhat adalah nilai prediksi utama dari Prophet

    rmse = np.sqrt(mean_squared_error(y_asli, y_prediksi))
    mae = mean_absolute_error(y_asli, y_prediksi)

    print("\n" + "="*50)
    print("HASIL EVALUASI MODEL (FACEBOOK PROPHET)")
    print("="*50)
    print(f"Batas Waktu Training : Dari {train_df['ds'].min().date()} s/d {train_df['ds'].max().date()}")
    print(f"Batas Waktu Testing  : Dari {test_df['ds'].min().date()} s/d {test_df['ds'].max().date()}")
    print(f"Root Mean Squared Error (RMSE) : Rp {rmse:,.2f}")
    print(f"Mean Absolute Error (MAE)      : Rp {mae:,.2f}")
    print("Catatan: MAE menunjukkan rata-rata melesetnya tebakan model dalam Rupiah.")
    print("="*50)

    # Mengembalikan model yang sudah dilatih dengan SELURUH DATA untuk peramalan masa depan
    print("Melatih ulang model dengan 100% data untuk peramalan masa depan...")
    final_model = Prophet(daily_seasonality=False, yearly_seasonality=False, weekly_seasonality=True)
    final_model.fit(df_prophet)

    return final_model

# ==============================================================================
# 4. FUTURE FORECASTING (MERAMALKAN MASA DEPAN)
# ==============================================================================
def forecast_future_sales(model, horizon_days=30):
    """
    Fungsi ini meramalkan penjualan untuk X hari ke depan.
    Menghasilkan point estimate (yhat), lower bound (yhat_lower), dan upper bound (yhat_upper)
    Sesuai dengan skema Database MongoDB di dokumen PDF Anda.
    """
    print(f"[4] Meramalkan penjualan untuk {horizon_days} hari ke depan...")

    # Membuat kalender masa depan
    future_dates = model.make_future_dataframe(periods=horizon_days, freq='D')

    # Melakukan peramalan
    forecast = model.predict(future_dates)

    # Mengambil hanya data masa depan (hasil ramalan baru)
    hasil_ramalan = forecast.tail(horizon_days)[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]

    print("\nINSIGHT BISNIS: Prediksi 5 Hari Pertama di Masa Depan:")
    print(hasil_ramalan.head(5).to_string(index=False))

    print("\nINFO: Format data ini sangat siap untuk di-push ke collection 'forecast_results' di MongoDB.")

    return forecast

# ==============================================================================
# EKSEKUSI PIPELINE UTAMA
# ==============================================================================
if __name__ == "__main__":
    print("=== PROPHET AI FORECASTING PIPELINE DIMULAI ===\n")

    # 1. Load Data
    df_mentah = load_and_preprocess_data()
    # Simpan df_mentah setelah di-load dan preprocess (khusus pipeline Prophet)
    df_mentah.to_csv('df_mentah_prophet_pipeline.csv', index=False)
    print("df_mentah (Prophet Pipeline) berhasil disimpan ke 'df_mentah_prophet_pipeline.csv'")

    # 2. Transformasi ke format Prophet
    df_prophet = prepare_prophet_data(df_mentah)

    # Jika Prophet terinstall, jalankan pipeline utama
    if 'Prophet' in globals():
        # 3. Train & Evaluate
        prophet_model = train_and_evaluate_prophet(df_prophet)

        # Simpan prophet_model
        with open('prophet_model.pkl', 'wb') as f:
            pickle.dump(prophet_model, f)
        print("Model Prophet berhasil disimpan ke 'prophet_model.pkl'")

        # 4. Ramalkan 30 Hari ke Depan (Menuju akhir Februari/Maret 2026)
        hasil_forecast = forecast_future_sales(prophet_model, horizon_days=30)

        print("\n=== PIPELINE SELESAI ===")
        print("Anda dapat menggunakan objek 'hasil_forecast' untuk divisualisasikan di Power BI atau Tableau!")
    else:
        print("\nPipeline terhenti karena library 'prophet' belum terinstall.")

"""### Visualisasi Hasil Peramalan dengan Prophet

Berikut adalah visualisasi dari prediksi penjualan harian dan komponen-komponen yang terdeteksi oleh model Prophet.
"""

fig1 = prophet_model.plot(hasil_forecast)
plt.title('Prediksi Penjualan Harian dengan Prophet')
plt.xlabel('Tanggal')
plt.ylabel('Total Penjualan (Rp)')
plt.show()

fig2 = prophet_model.plot_components(hasil_forecast)
plt.show()